import SubscribeForm from '../../../../subscribe-form';
import {notFound} from 'next/navigation';
import {Header,Footer,EntryCards,Empty} from '../../../../components';
import {parseReference,referenceLabel,chapterText,books} from '../../../../../lib/bible';
import {relatedTo} from '../../../../../lib/store';
import {contentLabel} from '../../../../../lib/content-kinds';
export const dynamic='force-dynamic';
async function passage(params:Promise<{book:string;chapter:string;range:string}>){const p=await params,b=books.find(b=>b.slug===p.book);const r=b&&parseReference(`${b.name} ${p.chapter}:${p.range}`);if(!r)notFound();return r}
export async function generateMetadata({params}:{params:Promise<{book:string;chapter:string;range:string}>}){const r=await passage(params);return {title:`Study ${referenceLabel(r)} | Hall Bible Commentary`,alternates:{canonical:`/study/${r.book}/${r.chapter}/${r.start}-${r.end}`}}}
export default async function Page({params}:{params:Promise<{book:string;chapter:string;range:string}>}){const r=await passage(params),all=await relatedTo(r.book,r.chapter),items=all.filter(c=>c.related.some((v:any)=>v.book===r.book&&v.chapter===r.chapter&&v.start<=r.end&&v.end>=r.start)),topics=[...new Set(items.flatMap(c=>c.topics||[]))] as string[];return <><Header/><main className='page'><span className='eyebrow'>STUDY THIS PASSAGE</span><h1>{referenceLabel(r)}</h1><section className='passage-card'>{chapterText(r.book,r.chapter).filter(v=>v.verse>=r.start&&v.verse<=r.end).map(v=><p key={v.verse}><sup>{v.verse}</sup> {v.text}</p>)}<a href={`/bible/${r.book}/${r.chapter}#verse-${r.start}-${r.end}`}>Read in context · WEB →</a></section>{!items.length&&<Empty text='There is no published teaching connected to this passage yet.'/>}{['commentary','sermon','blog','devotional','question'].map(kind=>{const group=items.filter(c=>c.kind===kind);return group.length?<section key={kind}><h2>{contentLabel(kind)}</h2><EntryCards items={group.slice(0,12)}/></section>:null})}{topics.length>0&&<section><h2>Connected topics</h2><div className='tags'>{topics.map(t=><a key={t} href={'/topics/'+encodeURIComponent(t)}>{t}</a>)}</div></section>}<SubscribeForm sourceType='study'/></main><Footer/></>}
