'use client';
import {useEffect,useRef,useState} from 'react';
import {EditorContent,useEditor} from '@tiptap/react';
import StarterKit from '@tiptap/starter-kit';
import Highlight from '@tiptap/extension-highlight';
import Image from '@tiptap/extension-image';
import TextAlign from '@tiptap/extension-text-align';
import TaskList from '@tiptap/extension-task-list';
import TaskItem from '@tiptap/extension-task-item';
import {TableKit} from '@tiptap/extension-table';
import Youtube from '@tiptap/extension-youtube';
import {RICH,toHTML,plainText,videoURL} from '../../lib/rich-content';
import Markdown from '../markdown';

type Props={value:string;onChange:(s:string)=>void;draftKey:string;label?:string;name?:string};
export default function RichEditor({value,onChange,draftKey,label='Teaching',name}:Props){
 const [mode,setMode]=useState('visual'),[panel,setPanel]=useState(''),[input,setInput]=useState(''),[alt,setAlt]=useState(''),[message,setMessage]=useState(''),[saving,setSaving]=useState(''),[busy,setBusy]=useState(false),[full,setFull]=useState(false),[versions,setVersions]=useState<any[]>([]),[library,setLibrary]=useState<any[]>([]),[media,setMedia]=useState<any[]>([]),[query,setQuery]=useState(''),[revision,bump]=useState(0);
 const current=useRef(value),changed=useRef(false),changeRef=useRef(onChange);changeRef.current=onChange;
 const editor=useEditor({immediatelyRender:false,extensions:[StarterKit.configure({link:{openOnClick:false}}),Highlight.configure({multicolor:true}),Image.configure({allowBase64:false}),TextAlign.configure({types:['heading','paragraph']}),TaskList,TaskItem.configure({nested:true}),TableKit,Youtube.configure({nocookie:true,controls:true})],content:toHTML(value),editorProps:{attributes:{role:'textbox','aria-label':label,'aria-multiline':'true',class:'rich-document'}},onUpdate:({editor})=>{const next=RICH+editor.getHTML();current.current=next;changed.current=true;changeRef.current(next);bump(n=>n+1)},onSelectionUpdate:()=>bump(n=>n+1),onTransaction:()=>bump(n=>n+1)},[]);
 useEffect(()=>{if(editor&&value!==current.current){current.current=value;editor.commands.setContent(toHTML(value),{emitUpdate:false});bump(n=>n+1)}},[value,editor]);
 useEffect(()=>{if(!changed.current)return;setSaving('Unsaved recovery copy…');const body=value;const timer=setTimeout(async()=>{try{await request('/api/editor-drafts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({key:draftKey,body})});setSaving('Recovery copy saved · use Save draft or Publish to save the entry')}catch{setSaving('Recovery unavailable · use Save draft to keep your work')}},1600);return()=>clearTimeout(timer)},[value,draftKey]);
 useEffect(()=>{if(!full)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')setFull(false)};window.addEventListener('keydown',escape);return()=>{document.body.style.overflow=old;window.removeEventListener('keydown',escape)}},[full]);
 async function request(url:string,init?:RequestInit){const r=await fetch(url,init);const d:any=await r.json();if(!r.ok)throw Error(d.error||'This action could not be completed.');return d}
 async function task(fn:()=>Promise<void>){setBusy(true);setMessage('');try{await fn()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 function show(next:string){setPanel(panel===next?'':next);setInput('');setMessage('');if(next==='history')task(async()=>setVersions((await request('/api/editor-drafts?key='+encodeURIComponent(draftKey))).versions));if(next==='library')task(async()=>setLibrary(await request('/api/content')));if(next==='image')task(async()=>setMedia(await request('/api/media')))}
 function insert(html:string){editor?.chain().focus().insertContent(html).run();setPanel('')}
 function exportFile(format:'html'|'txt'){const contents=format==='html'?'<!doctype html><html lang="en"><meta charset="utf-8"><title>Teaching export</title><body>'+toHTML(value)+'</body></html>':plainText(value);const url=URL.createObjectURL(new Blob([contents],{type:format==='html'?'text/html':'text/plain'}));const a=document.createElement('a');a.href=url;a.download='teaching.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
 const words=plainText(value).split(/\s+/).filter(Boolean).length;
 const button=(title:string,action:()=>void,active=false,disabled=false)=><button type="button" key={title} className={active?'selected':''} title={title} aria-label={title} aria-pressed={active} disabled={disabled} onClick={action}>{title}</button>;
 if(!editor)return <p>Loading writing tools…</p>;
 return <div className={'rich-editor'+(full?' rich-fullscreen':'')}>
 {name&&<input type="hidden" name={name} value={value}/>}
 <div className="rich-heading"><strong>{label}</strong><div className="rich-modes">{['visual','source','preview'].map(m=><button type="button" aria-pressed={mode===m} key={m} onClick={()=>setMode(m)}>{m==='source'?'Markdown / HTML':m[0].toUpperCase()+m.slice(1)}</button>)}<button type="button" onClick={()=>setFull(!full)}>{full?'Exit full screen':'Full screen'}</button></div></div>
 {mode==='visual'&&<><div className="rich-toolbar" role="toolbar" aria-label="Text formatting">
 {button('Undo',()=>editor.chain().focus().undo().run(),false,!editor.can().undo())}{button('Redo',()=>editor.chain().focus().redo().run(),false,!editor.can().redo())}
 <select aria-label="Paragraph style" value={[1,2,3].find(level=>editor.isActive('heading',{level}))||0} onChange={e=>e.target.value==='0'?editor.chain().focus().setParagraph().run():editor.chain().focus().toggleHeading({level:Number(e.target.value) as 1|2|3}).run()}><option value="0">Paragraph</option><option value="1">Heading 1</option><option value="2">Heading 2</option><option value="3">Heading 3</option></select>
 {button('Bold',()=>editor.chain().focus().toggleBold().run(),editor.isActive('bold'))}{button('Italic',()=>editor.chain().focus().toggleItalic().run(),editor.isActive('italic'))}{button('Underline',()=>editor.chain().focus().toggleUnderline().run(),editor.isActive('underline'))}{button('Strikethrough',()=>editor.chain().focus().toggleStrike().run(),editor.isActive('strike'))}{button('Highlight',()=>editor.chain().focus().toggleHighlight({color:'#dbeafe'}).run(),editor.isActive('highlight'))}
 {button('Bullets',()=>editor.chain().focus().toggleBulletList().run(),editor.isActive('bulletList'))}{button('Numbered list',()=>editor.chain().focus().toggleOrderedList().run(),editor.isActive('orderedList'))}{button('Checklist',()=>editor.chain().focus().toggleTaskList().run(),editor.isActive('taskList'))}{button('Quote',()=>editor.chain().focus().toggleBlockquote().run(),editor.isActive('blockquote'))}{button('Divider',()=>editor.chain().focus().setHorizontalRule().run())}
 {['left','center','right','justify'].map(align=>button('Align '+align,()=>editor.chain().focus().setTextAlign(align).run(),editor.isActive({textAlign:align})))}
 {button('Clear formatting',()=>editor.chain().focus().unsetAllMarks().clearNodes().run())}{button('Link',()=>show('link'),panel==='link')}{button('Remove link',()=>editor.chain().focus().unsetLink().run(),false,!editor.isActive('link'))}
 {button('Image',()=>show('image'),panel==='image')}{button('YouTube',()=>show('video'),panel==='video')}{button('Scripture',()=>show('scripture'),panel==='scripture')}{button('From library',()=>show('library'),panel==='library')}{button('Table',()=>editor.chain().focus().insertTable({rows:3,cols:3,withHeaderRow:true}).run())}
 {editor.isActive('table')&&<>{button('Add row',()=>editor.chain().focus().addRowAfter().run())}{button('Add column',()=>editor.chain().focus().addColumnAfter().run())}{button('Remove row',()=>editor.chain().focus().deleteRow().run())}{button('Remove column',()=>editor.chain().focus().deleteColumn().run())}{button('Merge cells',()=>editor.chain().focus().mergeCells().run())}{button('Split cell',()=>editor.chain().focus().splitCell().run())}{button('Remove table',()=>editor.chain().focus().deleteTable().run())}</>}
 </div>
 {panel&&<div className="rich-insert"><div className="rich-heading"><strong>{({image:'Add an image',video:'Embed YouTube',scripture:'Insert World English Bible',library:'Insert from your library',link:'Add a link',history:'Recovery history'} as any)[panel]}</strong><button type="button" onClick={()=>setPanel('')}>Close tools</button></div>
 {['link','video','scripture'].includes(panel)&&<><label className="field"><span>{panel==='scripture'?'Scripture reference':panel==='link'?'Link address':'YouTube link'}</span><input value={input} onChange={e=>setInput(e.target.value)} placeholder={panel==='scripture'?'John 3:16–18':'https://…'}/></label><div className="toolbar"><button type="button" className="button" disabled={busy} onClick={()=>task(async()=>{if(panel==='link'){const u=new URL(input,window.location.origin);if(!['https:','http:','mailto:'].includes(u.protocol))throw Error('Use an HTTPS, HTTP, email, or local link.');if(editor.state.selection.empty)editor.chain().focus().insertContent([{type:'text',text:input,marks:[{type:'link',attrs:{href:input}}]}]).run();else editor.chain().focus().extendMarkRange('link').setLink({href:input}).run();setPanel('')}else if(panel==='video'){const src=videoURL(input);if(!src)throw Error('Enter a valid YouTube video link.');editor.commands.setYoutubeVideo({src,width:640,height:360});setPanel('')}else{const d=await request('/api/scripture?reference='+encodeURIComponent(input));editor.chain().focus().insertContent([{type:'paragraph',content:[{type:'text',text:d.label+' · WEB',marks:[{type:'link',attrs:{href:d.url}}]}]},{type:'blockquote',content:d.verses.map((v:any)=>({type:'paragraph',content:[{type:'text',text:v.verse+' '+v.text}]}))}]).run();setPanel('')}})}>Insert {panel==='scripture'?'passage':'into teaching'}</button>{panel==='scripture'&&<button type="button" className="button" onClick={()=>task(async()=>{const d=await request('/api/scripture?reference='+encodeURIComponent(input));editor.chain().focus().insertContent([{type:'text',text:d.label,marks:[{type:'link',attrs:{href:d.url}}]}]).run();setPanel('')})}>Insert reference only</button>}</div>{panel==='video'&&<p className="help">Readers choose to load the player before YouTube is contacted.</p>}</>}
 {panel==='image'&&<><label className="field"><span>Image description (alt text)</span><input value={alt} onChange={e=>setAlt(e.target.value)} placeholder="Describe what the image shows"/></label><label className="field"><span>Upload from your device</span><input type="file" accept="image/jpeg,image/png,image/webp,image/gif" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(!f)return;task(async()=>{const fd=new FormData();fd.set('file',f);const d=await request('/api/media',{method:'POST',body:fd});editor.chain().focus().setImage({src:d.url,alt}).run();setPanel('')});e.target.value=''}}/></label><p className="help">JPEG, PNG, WebP or GIF · Up to 4 MB. Images are optimized; animated GIFs become a still image. Uploaded images stay private until included in published teaching.</p><label className="field"><span>Or use an HTTPS image address</span><input value={input} onChange={e=>setInput(e.target.value)} placeholder="https://…"/></label><button type="button" className="button" onClick={()=>task(async()=>{if(new URL(input).protocol!=='https:')throw Error('Use an HTTPS image address.');editor.chain().focus().setImage({src:input,alt}).run();setPanel('')})}>Insert image address</button>{editor.isActive('image')&&<button type="button" className="button" onClick={()=>editor.chain().focus().updateAttributes('image',{alt}).run()}>Update selected image description</button>}<div className="media-library">{media.map(m=><button type="button" key={m.id} onClick={()=>{editor.chain().focus().setImage({src:m.url,alt:alt||m.name}).run();setPanel('')}}><img src={m.url} alt=""/><span>{m.name}</span></button>)}</div></>}
 {panel==='library'&&<><input aria-label="Search your library" placeholder="Search your approved teaching…" value={query} onChange={e=>setQuery(e.target.value)}/><p className="help">Only published original teaching is offered here. Inserted text becomes part of this draft and still needs your review.</p>{library.filter(x=>x.status==='published'&&(!x.publish_date||x.publish_date<=new Date().toISOString())&&(!x.attribution||JSON.parse(typeof x.attribution==='string'?x.attribution:JSON.stringify(x.attribution)).origin==='aaron')&&x.title.toLowerCase().includes(query.toLowerCase())).map(x=><button type="button" className="library-insert" key={x.id} onClick={()=>insert(toHTML(x.body))}>{x.title} · Insert</button>)}</>}
 {panel==='history'&&<><p className="help">Up to 20 body recovery copies. Restoring changes this editor; it does not publish. Titles and other fields are saved using the entry’s Save draft button.</p>{versions.length?versions.map((v,i)=><details key={v.at+i}><summary>{new Date(v.at).toLocaleString()}</summary><p>{plainText(v.body).slice(0,250)}</p><button type="button" className="button" onClick={()=>{changed.current=true;changeRef.current(v.body);setPanel('')}}>Restore this body</button></details>):<p>No recovery copies yet.</p>}</>}
 {message&&<p role="alert">{message}</p>}{busy&&<p role="status">Working…</p>}</div>}
 <EditorContent editor={editor}/></>}
 {mode==='source'&&<><p className="help">Existing Markdown remains supported. Visual edits use safe HTML with a format marker. Keep the marker when editing HTML. Scripts and unsupported embeds are removed.</p><textarea className="body-editor" aria-label={label+' source'} value={value} onChange={e=>{changed.current=true;changeRef.current(e.target.value)}}/></>}
 {mode==='preview'&&<Markdown text={value}/>}
 <div className="rich-status"><span>{words.toLocaleString()} words · {Math.max(1,Math.ceil(words/220))} min read · {Math.max(1,Math.ceil(words/130))} min spoken</span><div className="rich-modes"><button type="button" onClick={()=>{setMode('visual');show('history')}}>History</button><button type="button" onClick={()=>exportFile('html')}>Export HTML</button><button type="button" onClick={()=>exportFile('txt')}>Export text</button></div><small role="status">{saving||'Changes stay in this editor until you save the entry.'}</small></div>
 </div>
}
export function FormRichEditor({initial='',name,draftKey,label}:{initial?:string;name:string;draftKey:string;label:string}){const [value,setValue]=useState(initial);return <RichEditor value={value} onChange={setValue} name={name} draftKey={draftKey} label={label}/>}
