'use client';
import {useState} from 'react';
import books from '../../data/books.json';
import {normalizeLocation,verseNumbers,type Location} from '../../lib/commentary-location';
const types=[['verse','One verse'],['range','Multiple verses'],['chapter','Chapter overview'],['book','Book introduction']];
export default function ScriptureSelector({value,onChange}:{value:Location;onChange:(v:Location)=>void}){
 const [query,setQuery]=useState(''),[reference,setReference]=useState(''),[error,setError]=useState('');const location=normalizeLocation(value,{}),book=books.find(b=>b.slug===location.book)!,verses=verseNumbers(book.slug,location.chapter||1);
 const update=(patch:Partial<Location>)=>{setError('');onChange(normalizeLocation(location,patch))};
 const label=book.name+(location.entry_type==='book'?' · Book introduction':` ${location.chapter}`+(location.entry_type==='chapter'?' · Chapter overview':`:${location.verse_start}`+(location.entry_type==='range'&&location.verse_end!==location.verse_start?`–${location.verse_end}`:'')));
 function jump(){const match=reference.trim().match(/^(.+?)\s+(\d+)(?::(\d+)(?:\s*[-–]\s*(\d+))?)?$/),b=books.find(b=>b.name.toLowerCase()===(match?.[1]||reference.trim()).toLowerCase());if(!b){setError('Use a full book name, for example John 3:16–18 or 1 John 2.');return}if(!match){update({book:b.slug,entry_type:'book'});return}const chapter=Number(match[2]),start=Number(match[3]||1),end=Number(match[4]||start),numbers=verseNumbers(b.slug,chapter);if(!numbers.includes(start)||!numbers.includes(end)||end<start){setError('That chapter or verse range does not exist.');return}onChange({book:b.slug,chapter,entry_type:match[4]?'range':match[3]?'verse':'chapter',verse_start:match[3]?start:null,verse_end:match[3]?end:null});setQuery('');setError('')}
 return <section className="scripture-selector"><h3>Where does this commentary belong?</h3><div className="field-row"><label className="field">Quick reference<input value={reference} onChange={e=>setReference(e.target.value)} placeholder="John 3:16–18 or Psalms 23" onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();jump()}}}/></label><button type="button" className="button" onClick={jump}>Use reference</button></div>{error&&<p role="alert">{error}</p>}<div className="location-types" role="group" aria-label="Commentary coverage">{types.map(([type,title])=><button type="button" key={type} aria-pressed={location.entry_type===type} onClick={()=>update({entry_type:type})}>{title}</button>)}</div><div className="form-grid"><label className="field">Find a book<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search Bible books"/></label><label className="field">Bible book<select value={book.slug} onChange={e=>{update({book:e.target.value});setQuery('')}}>{['Old Testament','New Testament'].map(testament=><optgroup label={testament} key={testament}>{books.filter(b=>b.testament===testament&&(b.slug===book.slug||b.name.toLowerCase().includes(query.toLowerCase()))).map(b=><option value={b.slug} key={b.slug}>{b.name}</option>)}</optgroup>)}</select></label>{location.entry_type!=='book'&&<label className="field">Chapter<select value={location.chapter||1} onChange={e=>update({chapter:Number(e.target.value)})}>{Array.from({length:book.chapters},(_,i)=><option key={i+1} value={i+1}>Chapter {i+1}</option>)}</select></label>}{['verse','range'].includes(location.entry_type)&&<label className="field">{location.entry_type==='verse'?'Verse':'First verse'}<select value={location.verse_start||1} onChange={e=>update({verse_start:Number(e.target.value)})}>{verses.map(n=><option key={n} value={n}>Verse {n}</option>)}</select></label>}{location.entry_type==='range'&&<label className="field">Last verse<select value={location.verse_end||1} onChange={e=>update({verse_end:Number(e.target.value)})}>{verses.filter(n=>n>=(location.verse_start||1)).map(n=><option key={n} value={n}>Verse {n}</option>)}</select></label>}</div><div className="notice"><strong>{label}</strong><p>{location.entry_type==='book'?'Linked throughout this book.':location.entry_type==='chapter'?'Linked to every verse in this chapter.':'Linked to the selected verses within this chapter.'}</p><a href={'/bible/'+book.slug+'/'+(location.chapter||1)+(location.verse_start?'#verse-'+location.verse_start:'')} target="_blank" rel="noopener noreferrer">Read this passage ↗</a></div></section>
}
