'use client';
import {socialImage,SITE_ORIGIN} from '../../lib/public-url';
import {useEffect,useState} from 'react';
import {emptySEO,type SEO} from '../../lib/seo-types';
export default function SEOEditor({path}:{path?:string}){
 const [address,setAddress]=useState(path||'/'),[loadedPath,setLoadedPath]=useState(''),[seo,setSEO]=useState<SEO>(emptySEO),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function load(address:string){setBusy(true);setMessage('');try{const r=await fetch('/api/seo?path='+encodeURIComponent(address)),data:any=await r.json();if(!r.ok)throw Error(data.error);setSEO(data);setLoadedPath(address)}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 useEffect(()=>{load(path||'/')},[path]);
 return <section className="editor-panel"><h3>Search & social sharing</h3><p className="help">Blank fields use the page’s default title and description. SEO changes are saved separately from the entry. Drafts remain private.</p>{!path&&<label className="field">Page path<input value={address} onChange={e=>setAddress(e.target.value)} placeholder="/about"/><button type="button" className="button" disabled={busy} onClick={()=>load(address)}>Load page settings</button></label>}{(['title','description','image'] as const).map(key=><label className="field" key={key}>{key==='title'?'SEO title':key==='description'?'Search description':'Social image URL'}<input type={key==='image'?'url':'text'} value={seo[key]} maxLength={key==='title'?120:key==='description'?320:2000} onChange={e=>setSEO({...seo,[key]:e.target.value})}/></label>)}<div className="card"><h4>Social preview</h4><img alt="Social sharing preview" style={{width:'100%',maxWidth:600}} src={seo.image||socialImage(seo.title||'Hall Bible Commentary',seo.description)}/><label className="field">Upload a social image<input type="file" accept="image/jpeg,image/png,image/webp" onChange={async e=>{const f=e.target.files?.[0];if(!f)return;setBusy(true);try{const form=new FormData();form.set('file',f);const r=await fetch('/api/media',{method:'POST',body:form});const d:any=await r.json();if(!r.ok)throw Error(d.error);setSEO({...seo,image:SITE_ORIGIN+d.url})}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}/></label><button type="button" className="button" onClick={()=>setSEO({...seo,image:''})}>Use automatic social image</button><p>Save SEO settings to apply your choice.</p></div><label className="switch-line"><input type="checkbox" checked={seo.noindex} onChange={e=>setSEO({...seo,noindex:e.target.checked})}/>Hide this page from search engine results (noindex)</label><p className="help">This does not make a published page private. Canonical URLs follow the permanent page address automatically.</p><div className="card"><strong>{seo.title||'Default page title'}</strong><p>{loadedPath}</p><p>{seo.description||'Default page description'}</p></div><button type="button" className="button primary" disabled={busy||!loadedPath||address!==loadedPath} onClick={async()=>{setBusy(true);setMessage('');try{const r=await fetch('/api/seo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({path:loadedPath,seo})});const data:any=await r.json();if(!r.ok)throw Error(data.error);setMessage('SEO settings saved. Search engines may take time to refresh their results.')}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}}>Save SEO settings</button>{message&&<p role="status">{message}</p>}</section>
}
