'use client';
import parse,{Element,Text,domToReact,type DOMNode} from 'html-react-parser';
import {RICH,toHTML} from '../lib/rich-content';
import EmbeddedVideo from './embedded-video';
import ReactMarkdown from 'react-markdown';import remarkGfm from 'remark-gfm';import books from '../data/books.json';
import verses from '../data/verses';
import {useState} from 'react';
function ScriptureLink({href,children}:any){const [open,setOpen]=useState(false);const m=href?.match(/^\/bible\/([^/]+)\/(\d+)#verse-(\d+)/);if(!m)return <a href={href} rel={href?.startsWith('http')?'noopener noreferrer':undefined}>{children}</a>;const row=verses.find(v=>v.book===m[1]&&v.chapter===+m[2]&&v.verse===+m[3]);return <span className="scripture-inline"><button type="button" className="scripture-link" onClick={()=>setOpen((v:boolean)=>!v)}>{children}</button>{open&&row&&<span className="scripture-popover"><strong>{children}</strong><span>{row.text}</span><a href={href}>Open Bible passage →</a></span>}</span>}
export function linkScriptures(text:string){const names=[...books].sort((a,b)=>b.name.length-a.name.length).map(b=>b.name).join('|');const re=new RegExp('\\b('+names+')\\s+(\\d+):(\\d+)(?:[–-](\\d+))?','gi');return text.split(/(```[\s\S]*?```|`[^`]*`|\[[^\]]*\]\([^)]*\))/g).map((part,i)=>i%2?part:part.replace(re,(m,name,c,v)=>{const b=books.find(b=>b.name.toLowerCase()===name.toLowerCase());return `[${m}](/bible/${b?.slug}/${c}#verse-${v})`})).join('')}
export default function Markdown({text}:{text:string}){if(text.startsWith(RICH))return <div className="markdown">{parse(toHTML(text),{replace(node){if(node instanceof Element&&node.name==='iframe')return <EmbeddedVideo src={node.attribs.src}/>;if(node instanceof Text&&node.data.trim()){let parent=node.parent;while(parent){if(parent instanceof Element&&['a','code','pre'].includes(parent.name))return;parent=parent.parent}const linked=linkScriptures(node.data);if(linked!==node.data)return <ReactMarkdown components={{p:({children})=><>{children}</>,a:ScriptureLink}}>{linked}</ReactMarkdown>}}})}</div>;return <div className="markdown"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:ScriptureLink}}>{linkScriptures(text)}</ReactMarkdown></div>}
