import {createHash} from 'node:crypto';
import {db,decode} from './store';
import {plainText,RICH,toHTML} from './rich-content';
import {referencesIn,referenceLabel,parseReference} from './bible';
import {classifications,originalClasses,type KnowledgeSource,type Segment} from './knowledge-types';
export function fingerprint(s:string){return createHash('sha256').update(s).digest('hex')}
export async function getPrivate<T=any>(id:string):Promise<T|null>{const row=await db().prepare('SELECT value FROM site_settings WHERE id=?').bind(id).first<any>();return row?JSON.parse(row.value):null}
export function insertPrivate(id:string,value:any){return db().prepare('INSERT INTO site_settings (id,value,updated_at) VALUES (?,?,?)').bind(id,JSON.stringify(value),new Date().toISOString())}
export async function putPrivate(id:string,value:any){await db().prepare('INSERT INTO site_settings (id,value,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at').bind(id,JSON.stringify(value),new Date().toISOString()).run()}
export async function listPrivate(prefix:string){return (await db().prepare('SELECT id,value FROM site_settings WHERE id LIKE ? ORDER BY updated_at DESC').bind(prefix+'%').all()).results.map((r:any)=>JSON.parse(r.value))}
export function sourceText(value:string){return value.startsWith(RICH)?toHTML(value).replace(/<blockquote[^>]*>/g,'\n\n[QUOTATION]\n').replace(/<iframe[^>]*src="([^"]*)"[^>]*>[\s\S]*?<\/iframe>/g,'\n\n[EMBED] $1\n\n').replace(/<img[^>]*src="([^"]*)"[^>]*>/g,'\n\n[EMBED] $1\n\n').replace(/<a[^>]*href="(https?:[^" ]*)"[^>]*>(.*?)<\/a>/g,'$2 [EXTERNAL LINK: $1]').split(/\n\n/).map(s=>plainText(RICH+s)).join('\n\n'):value}
export function segmentSource(text:string):Segment[]{let inherited='';const segments:Segment[]=[];for(const m of text.matchAll(/[^\r\n]+(?:\r?\n(?!\r?\n)[^\r\n]+)*/g)){const paragraph=m[0];const exact=parseReference(paragraph.trim());if(exact)inherited=referenceLabel(exact);const parts=[...paragraph.matchAll(/https?:\/\/[^\s<>\])]+|[“"][^”"\n]{3,}[”"]|[^“"\n]+|[“"]/g)];for(const part of parts){const body=part[0].trim();if(!body)continue;const flags:string[]=[];let classification:Segment['classification']='unknown';if(/^https?:/.test(body)){classification='external_link';flags.push('URL is metadata only; never fetched')}else if(/^\[EMBED\]/.test(body)){classification='embedded';flags.push('Embedded material')}else if(/^[“"]|^\s*>|\[QUOTATION\]/.test(body)){classification='external_quote';flags.push('Quotation formatting detected')}else if(exact){classification='scripture';flags.push('Scripture reference heading')}else if(/\b(according to|quoted|quotation|wrote|writes|once said|cited|citation|copyright|source:)\b/i.test(body)){flags.push('Attribution language detected')}if(/\b(study found|research|statistics?|percent|survey|\d+%|lyrics)\b/i.test(body))flags.push('Research, statistics, or lyrics need verification');const refs=referencesIn(body);const start=m.index!+part.index!+part[0].indexOf(body);segments.push({id:fingerprint(start+':'+body).slice(0,24),text:body,start,end:start+body.length,classification,verifiedBy:null,verifiedAt:null,attribution:'',reference:refs[0]?referenceLabel(refs[0]):inherited,role:exact?'passing':'unassigned',flags})}}return segments}
export async function rawSources(){const sermons=(await db().prepare('SELECT * FROM sermons').all()).results as any[];const entries=(await db().prepare("SELECT * FROM content WHERE status='published' AND (publish_date IS NULL OR publish_date<=?)").bind(new Date().toISOString()).all()).results as any[];return [...sermons.map(s=>({id:'sermon-'+s.id,recordId:s.id,kind:'sermon',title:s.title,body:s.text,approved:false})),...entries.filter(c=>{try{return JSON.parse(c.attribution||'{}').origin==='aaron'}catch{return false}}).map(c=>({id:'content-'+c.id,recordId:c.id,kind:c.kind==='blog'?'article':'commentary',title:c.title,body:c.body,approved:true}))]}
let recentKnowledge:{at:number;value:KnowledgeSource[]}|null=null;
export async function syncKnowledge(){if(recentKnowledge&&Date.now()-recentKnowledge.at<15000)return recentKnowledge.value;const records=await rawSources();const result:KnowledgeSource[]=[];for(const record of records){const text=sourceText(record.body),hash=fingerprint(text),existing=await getPrivate<KnowledgeSource>('kb:'+record.id);if(existing?.hash===hash){result.push({...existing,title:record.title});continue}const source:KnowledgeSource={...record,hash,text,segments:segmentSource(text),updatedAt:new Date().toISOString(),approved:record.approved};delete (source as any).body;await putPrivate('kb:'+record.id,source);await db().prepare('INSERT INTO site_settings (id,value,updated_at) VALUES (?,?,?) ON CONFLICT(id) DO NOTHING').bind('kb-snapshot:'+record.id+':'+hash,JSON.stringify(source),source.updatedAt).run();result.push(source)}recentKnowledge={at:Date.now(),value:result};return result}
export async function verifySegment(x:any,actor:string){const sources=await syncKnowledge();const source=sources.find(s=>s.id===x.sourceId);if(!source||source.hash!==x.hash)throw Error('The source changed. Reload and verify the current text.');const segment=source.segments.find(s=>s.id===x.segmentId);if(!segment||!classifications.includes(x.classification))throw Error('Choose a source segment and classification.');if(!['substantial','supporting','passing','unassigned'].includes(x.role))throw Error('Choose the passage relationship.');if(x.reference&&!parseReference(x.reference))throw Error('Enter a valid Scripture passage.');if(originalClasses.includes(x.classification)&&segment.flags.length&&!String(x.overrideReason||'').trim())throw Error('This segment has source warnings. Explain why you have verified that every word is yours, or classify it as external.');if(['external_quote','external_paraphrase','external_research'].includes(x.classification)&&!String(x.attribution||'').trim())throw Error('Name the original source or mark unknown.');Object.assign(segment,{classification:x.classification,reference:x.reference||'',role:x.role,attribution:String(x.attribution||'').slice(0,2000),overrideReason:String(x.overrideReason||'').slice(0,2000),verifiedBy:actor,verifiedAt:new Date().toISOString()});source.approved=true;await putPrivate('kb:'+source.id,source);await insertPrivate('kb-verification:'+crypto.randomUUID(),{sourceId:source.id,hash:source.hash,segment,actor,at:new Date().toISOString()}).run();return source}
export function eligible(source:KnowledgeSource,s:Segment){return source.approved&&!s.flags.length&&!s.attribution&&!!s.verifiedBy&&!!s.verifiedAt&&originalClasses.includes(s.classification)}
export async function voiceProfile(){const sources=await syncKnowledge();const selected=sources.flatMap(source=>source.segments.filter(s=>eligible(source,s)).map(segment=>({source,segment})));const hash=fingerprint(JSON.stringify(selected.map(x=>[x.source.hash,x.segment.id,x.segment.verifiedAt])));const prior=await getPrivate('voice:'+hash);if(prior)return prior;const modes=['commentary','sermon','article'].map(kind=>{const rows=selected.filter(x=>x.source.kind===kind);const text=rows.map(x=>x.segment.text).join(' '),words=text.match(/[\p{L}’'-]+/gu)||[];const freq=new Map<string,number>();words.filter(w=>w.length>4).forEach(w=>freq.set(w.toLowerCase(),(freq.get(w.toLowerCase())||0)+1));return {kind,segments:rows.length,words:words.length,averageSentenceWords:Math.round(words.length/Math.max(1,text.split(/[.!?]+/).filter(x=>x.trim()).length)),vocabulary:[...freq].sort((a,b)=>b[1]-a[1]).slice(0,30),examples:rows.slice(0,5).map(x=>({sourceId:x.source.id,title:x.source.title,segmentId:x.segment.id,text:x.segment.text}))}});const result={version:hash,createdAt:new Date().toISOString(),sources:selected.map(x=>({id:x.source.id,hash:x.source.hash,segmentId:x.segment.id})),modes,note:'Private reference profile, not model training. Only manually verified original segments are included. No inferred theological beliefs.'};await putPrivate('voice:'+hash,result);return result}
export function overlap(a:string,b:string){const x=parseReference(a),y=parseReference(b);return !!x&&!!y&&x.book===y.book&&x.chapter===y.chapter&&x.start<=y.end&&x.end>=y.start}
export async function retrieve(reference:string,query='',sourceIds?:string[]){const sources=await syncKnowledge();const words=new Set(query.toLowerCase().match(/[a-z]{4,}/g)||[]);return sources.filter(s=>!sourceIds||sourceIds.includes(s.id)).flatMap(source=>source.segments.filter(s=>eligible(source,s)&&s.role==='substantial'&&overlap(s.reference,reference)).map(segment=>({source,segment,score:({commentary:400,sermon:300,article:200} as any)[source.kind]||100}))).map(x=>({...x,score:x.score+[...words].filter(w=>x.segment.text.toLowerCase().includes(w)).length})).sort((a,b)=>b.score-a.score).slice(0,40)}
