import {commentarySlug} from './public-url';
import {env} from '@/lib/runtime';
export function db():D1Database{if(!env.DB)throw new Error('Storage is not available. Please try again later.');return env.DB}
export function decode(row:any){if(!row)return null;const d={...row};for(const k of ['topics','people','categories','related','provenance','tags'])if(k in d){try{d[k]=JSON.parse(d[k]||'[]')}catch{d[k]=[]}}return d}
function publicContent(row:any){const d=decode(row);delete d.provenance;delete d.generated_body;if(d.kind==='commentary')d.slug=commentarySlug(d);return d}
export async function published(kind?:string){if((env as any).APP_RUNTIME==='vercel'&&process.env.NODE_ENV==='production'&&!process.env.DATABASE_URL)return [];const q="SELECT * FROM content WHERE status='published' AND (publish_date IS NULL OR publish_date<=?)"+(kind?' AND kind=?':'')+' ORDER BY publish_date DESC';return (await db().prepare(q).bind(new Date().toISOString(),...(kind?[kind]:[])).all()).results.map(publicContent)}
export async function record(id:string){const exact=decode(await db().prepare('SELECT * FROM content WHERE id=? OR slug=?').bind(id,id).first());if(exact)return exact;return (await published('commentary')).find(c=>commentarySlug(c)===id)||null}
export async function relatedTo(book:string,chapter:number){const content=(await db().prepare("SELECT DISTINCT c.* FROM content c JOIN verse_mappings v ON v.content_id=c.id WHERE v.book=? AND v.chapter=? AND c.status='published' AND (c.publish_date IS NULL OR c.publish_date<=?) ORDER BY c.publish_date DESC").bind(book,chapter,new Date().toISOString()).all()).results.map(publicContent);const sermons=await publicSermons();return [...content,...sermons.filter(s=>s.related.some((r:any)=>r.book===book&&r.chapter===chapter))]}

export async function publicSermons(){if((env as any).APP_RUNTIME==='vercel'&&process.env.NODE_ENV==='production'&&!process.env.DATABASE_URL)return [];return (await db().prepare("SELECT id,title,passage,series,preached_at,tags,description,related,video_url,audio_url,created_at FROM sermons WHERE status='published' ORDER BY preached_at DESC").all()).results.map((row:any)=>{const r=decode(row);return {...r,kind:'sermon',slug:r.id,body:r.description||'',excerpt:r.description||r.passage,publish_date:r.preached_at||r.created_at,related:r.related||[],topics:r.tags,people:[],categories:[]}})}
