import {sqliteTable,text,integer,index,primaryKey} from 'drizzle-orm/sqlite-core';
export const content=sqliteTable('content',{id:text('id').primaryKey(),kind:text('kind').notNull(),title:text('title').notNull(),slug:text('slug').notNull().unique(),body:text('body').notNull(),excerpt:text('excerpt').notNull().default(''),status:text('status').notNull().default('draft'),entryType:text('entry_type').notNull().default('range'),book:text('book'),chapter:integer('chapter'),verseStart:integer('verse_start'),verseEnd:integer('verse_end'),topics:text('topics').notNull().default('[]'),people:text('people').notNull().default('[]'),series:text('series').notNull().default(''),categories:text('categories').notNull().default('[]'),related:text('related').notNull().default('[]'),sermonId:text('sermon_id'),provenance:text('provenance').notNull().default('[]'),generatedBody:text('generated_body'),attribution:text('attribution').notNull().default('{"origin":"aaron","author":"","title":"","url":"","note":""}'),publishDate:text('publish_date'),createdAt:text('created_at').notNull(),updatedAt:text('updated_at').notNull(),revision:integer('revision').notNull().default(1)},t=>[index('content_public').on(t.status,t.kind,t.publishDate),index('content_location').on(t.book,t.chapter)]);
export const verseMappings=sqliteTable('verse_mappings',{contentId:text('content_id').notNull().references(()=>content.id,{onDelete:'cascade'}),book:text('book').notNull(),chapter:integer('chapter').notNull(),start:integer('start').notNull(),end:integer('end').notNull()},t=>[index('verse_lookup').on(t.book,t.chapter,t.start,t.end)]);
export const sermons=sqliteTable('sermons',{id:text('id').primaryKey(),title:text('title').notNull(),passage:text('passage').notNull(),series:text('series').notNull().default(''),preachedAt:text('preached_at'),tags:text('tags').notNull().default('[]'),text:text('text').notNull(),uploadKey:text('upload_key'),filename:text('filename'),description:text('description').notNull().default(''),related:text('related').notNull().default('[]'),videoUrl:text('video_url').notNull().default(''),audioUrl:text('audio_url').notNull().default(''),status:text('status').notNull().default('private'),createdAt:text('created_at').notNull()});
export const taxonomy=sqliteTable('taxonomy',{id:text('id').primaryKey(),kind:text('kind').notNull(),name:text('name').notNull()},t=>[index('taxonomy_kind').on(t.kind)]);
export const audit=sqliteTable('audit',{id:text('id').primaryKey(),actor:text('actor').notNull(),action:text('action').notNull(),recordId:text('record_id').notNull(),createdAt:text('created_at').notNull()});

export const inquiries=sqliteTable('inquiries',{id:text('id').primaryKey(),kind:text('kind').notNull(),name:text('name').notNull(),email:text('email').notNull(),organization:text('organization').notNull().default(''),eventDate:text('event_date'),location:text('location').notNull().default(''),message:text('message').notNull(),status:text('status').notNull().default('new'),rateKey:text('rate_key').notNull(),createdAt:text('created_at').notNull()},t=>[index('inquiry_rate').on(t.rateKey,t.createdAt)]);

export const siteSettings=sqliteTable('site_settings',{id:text('id').primaryKey(),value:text('value').notNull(),updatedAt:text('updated_at').notNull()});
