import postgres from 'postgres';
import {createClient} from '@supabase/supabase-js';
import {mkdirSync,readdirSync,readFileSync,writeFileSync,existsSync,unlinkSync} from 'node:fs';
import path from 'node:path';
import {DatabaseSync} from 'node:sqlite';
let localDb:DatabaseSync|undefined;
const localAllowed=process.env.NODE_ENV==='development'&&process.env.LOCAL_DEMO==='true';
function local(){if(!localAllowed)throw Error('Configure DATABASE_URL before using the writing desk.');if(!localDb){mkdirSync(path.resolve('work/local'),{recursive:true});localDb=new DatabaseSync(path.resolve('work/local/library.sqlite'));localDb.exec('PRAGMA foreign_keys=ON');localDb.exec('CREATE TABLE IF NOT EXISTS _migrations (name TEXT PRIMARY KEY)')}for(const filename of readdirSync(path.resolve('drizzle')).filter(f=>f.endsWith('.sql')).sort())if(!localDb.prepare('SELECT name FROM _migrations WHERE name=?').get(filename)){localDb.exec(readFileSync(path.resolve('drizzle',filename),'utf8'));localDb.prepare('INSERT INTO _migrations VALUES (?)').run(filename)}return localDb}
let sql:ReturnType<typeof postgres>|undefined;
function pg(){if(!process.env.DATABASE_URL)throw Error('Configure DATABASE_URL before using the writing desk.');return sql||=postgres(process.env.DATABASE_URL,{prepare:false,max:3,ssl:'require',idle_timeout:20,connect_timeout:10})}
function convert(q:string){let n=0;return q.replace(/json_extract\(attribution,'\$\.origin'\)/g,"(attribution::jsonb->>'origin')").replace(/\b(start|end)\b/g,'"$1"').replace(/\?/g,()=>'$'+(++n))}
class Statement{constructor(public query:string,public values:any[]=[]){ }bind(...values:any[]){return new Statement(this.query,values)}async all<T=any>():Promise<{results:T[]}>{if(localAllowed&&!process.env.DATABASE_URL)return {results:local().prepare(this.query).all(...this.values) as T[]};return {results:await pg().unsafe(convert(this.query),this.values) as unknown as T[]}}async first<T=any>():Promise<T|null>{return (await this.all<T>()).results[0]||null}async run(){if(localAllowed&&!process.env.DATABASE_URL){const r=local().prepare(this.query).run(...this.values);return {success:true,meta:{changes:Number(r.changes)}}}const r=await pg().unsafe(convert(this.query),this.values);return {success:true,meta:{changes:r.count}}}}
const DB={prepare:(q:string)=>new Statement(q),async batch(statements:Statement[]){if(localAllowed&&!process.env.DATABASE_URL){const d=local();d.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());d.exec('COMMIT');return out}catch(e){d.exec('ROLLBACK');throw e}}return await pg().begin(async tx=>{const out=[];for(const s of statements){const r=await tx.unsafe(convert(s.query),s.values);out.push({success:true,meta:{changes:r.count}})}return out})}};
function storage(){if(!process.env.SUPABASE_URL||!process.env.SUPABASE_SERVICE_ROLE_KEY)throw Error('Configure Supabase private storage before uploading files.');return createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{persistSession:false,autoRefreshToken:false}}).storage.from('sermon-uploads')}
function localFile(key:string){if(!/^sermons\/[a-f0-9-]+\/source\.[a-z]+$/.test(key))throw Error('Invalid storage key.');return path.resolve('work/local/uploads',key)}
const BUCKET={async put(key:string,bytes:Uint8Array,options:any){if(localAllowed&&!process.env.SUPABASE_URL){const file=localFile(key);mkdirSync(path.dirname(file),{recursive:true});writeFileSync(file,bytes);return}const {error}=await storage().upload(key,bytes,{contentType:options?.httpMetadata?.contentType||'application/octet-stream',upsert:false});if(error)throw Error('Private upload failed. Please try again.');},async get(key:string){if(localAllowed&&!process.env.SUPABASE_URL){const file=localFile(key);if(!existsSync(file))return null;return {body:new Blob([readFileSync(file)]).stream()}}const {data,error}=await storage().download(key);if(error||!data)return null;return {body:data.stream()}},async delete(key:string){if(localAllowed&&!process.env.SUPABASE_URL){const file=localFile(key);if(existsSync(file))unlinkSync(file);return}const {error}=await storage().remove([key]);if(error)throw error}};
export const env={...process.env,DB,BUCKET,APP_RUNTIME:'vercel'} as any;
